// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello
List rcpp_hello();
RcppExport SEXP oligo_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}
// calcTm
NumericVector calcTm(CharacterVector seq, double dna_conc, double salt_conc, double divalent_conc, double dntp_conc, int tm_method, int salt_corrections);
RcppExport SEXP oligo_calcTm(SEXP seqSEXP, SEXP dna_concSEXP, SEXP salt_concSEXP, SEXP divalent_concSEXP, SEXP dntp_concSEXP, SEXP tm_methodSEXP, SEXP salt_correctionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type seq(seqSEXP);
    Rcpp::traits::input_parameter< double >::type dna_conc(dna_concSEXP);
    Rcpp::traits::input_parameter< double >::type salt_conc(salt_concSEXP);
    Rcpp::traits::input_parameter< double >::type divalent_conc(divalent_concSEXP);
    Rcpp::traits::input_parameter< double >::type dntp_conc(dntp_concSEXP);
    Rcpp::traits::input_parameter< int >::type tm_method(tm_methodSEXP);
    Rcpp::traits::input_parameter< int >::type salt_corrections(salt_correctionsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcTm(seq, dna_conc, salt_conc, divalent_conc, dntp_conc, tm_method, salt_corrections));
    return rcpp_result_gen;
END_RCPP
}
