# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('oligo_rcpp_hello', PACKAGE = 'oligo')
}

calcTm <- function(seq, dna_conc = 50, salt_conc = 50, divalent_conc = 0, dntp_conc = 0, tm_method = 0L, salt_corrections = 0L) {
    .Call('oligo_calcTm', PACKAGE = 'oligo', seq, dna_conc, salt_conc, divalent_conc, dntp_conc, tm_method, salt_corrections)
}

